// <auto-generated />
namespace TestePratico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Config_Table_Venda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Config_Table_Venda));
        
        string IMigrationMetadata.Id
        {
            get { return "201804230340082_Config_Table_Venda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
